Create a use case for the test component PostsListPage
lexisgasa/Blog-UI-TRP pull request #27
Opened 2024-08-24 09:49 UTC by lexisgasa

- Installed MSW to create a new use case for the component PostsListPage which was needed to retrieve data from an API.

2024-08-24 09:53 UTC, Guiblasco requested changes

2024-08-24 09:53 UTC, Guiblasco commented on src/post/pages/PostsListPage/PostsListPage.test.tsx
> +        name: "un elefante en la luna",
los titulos de los posts van en RegExp, podrias abtraerlas a una variable

2024-08-24 10:00 UTC, Guiblasco approved these changes

2024-08-24 10:00 UTC, lexisgasa commented on src/post/pages/PostsListPage/PostsListPage.test.tsx
> +        name: "un elefante en la luna",
Perfecto, voy a ello.

2024-08-24 10:00 UTC, merged

2024-08-24 10:59 UTC, the-refactor-project commented
Hay un commit descrito como "Refactor". No se sabe ni qué se ha refactorizado ni qué refactor se ha aplicado.

2024-08-24 11:00 UTC, the-refactor-project reviewed
Grandísima patada a la triple A.

2024-08-25 10:09 UTC, lexisgasa commented
> Hay un commit descrito como "Refactor". No se sabe ni qué se ha refactorizado ni qué refactor se ha aplicado.
![Screenshot 2024-08-25 at 12 09 00](https://github.com/user-attachments/assets/72c84933-2c1e-4a70-8dc6-b0dcf4e39161)

No está bien?
Lo de la triple A también lo comenté que se me pasó muy fuerte y tengo pendiente ajustarla para el siguiente caso de uso, cuando se testee la imagen.