Feature/post card
lexisgasa/Blog-UI-TRP pull request #7
Opened 2024-08-20 21:18 UTC by Guiblasco

Relocate in a folder of the name of the entity "Post"
Add lintstaged and configure vitest-coverage
Add NavMenu in Header component
Add Card component

2024-08-20 21:37 UTC, lexisgasa requested changes
Aparte de lo que te he comentado en cada línea, habría que añadir un meta description como vimos en clase, y pienso que tendríamos que decidir el tamaño de letra que pones ya que ahora mismo los posts son especialmente grandes en comparación a los links.

2024-08-20 21:37 UTC, lexisgasa commented on .gitignore
> +
este espacio no es necesario, no?

2024-08-20 21:37 UTC, lexisgasa commented on src/main.tsx
> +  </StrictMode>,
entiendo que no molesta esta coma pero se supone que no deberíamos de tocar nada por aquí..

2024-08-20 21:37 UTC, lexisgasa commented on src/post/components/Header/Header.css
> +  border-bottom: 3px solid var(--main-color);
si añadimos este `border-bottom` se superpone de una manera feota con el borde del link que hay en activo, hay que decidir cual se queda pero ambos no.

2024-08-20 21:47 UTC, Guiblasco commented on src/main.tsx
> +  </StrictMode>,
ha sido al guardar, al renombrar carpetas tenia la bolita de la muerte y he guardado y se formateó

2024-08-20 21:50 UTC, Guiblasco commented on src/post/components/Header/Header.css
> +  border-bottom: 3px solid var(--main-color);
corregido

2024-08-20 21:50 UTC, Guiblasco commented on .gitignore
> +
creo que nop!

2024-08-20 22:09 UTC, lexisgasa approved these changes

2024-08-20 22:21 UTC, merged

2024-08-21 02:23 UTC, the-refactor-project commented on src/post/components/App/App.tsx
> +      <Card title="La pequeña araña de 8 patas" />
¿Qué hace una card ahí en medio suelta ocupando todo el ancho? (feedback idéntico al del proyecto pasado donde se cometió exactamente el mismo error, feedback no integrado y no aplicado)

2024-08-21 02:23 UTC, the-refactor-project commented
Esta PR es un infierno de cambios no relacionados entre sí, es totalmente imposible hacerle una revisión en condiciones.

2024-08-21 09:00 UTC, Guiblasco commented on src/post/components/App/App.tsx
> +      <Card title="La pequeña araña de 8 patas" />
No debí pushear una prueba, lo tengo en cuenta para la próxima, además que hay que corregir unos errores

2024-08-21 13:00 UTC, Guiblasco commented
Iba corrigiendo los errores porque no vi todos los comits de una, para la próxima ya lo sé

2024-08-21 13:01 UTC, Guiblasco commented
> Aparte de lo que te he comentado en cada línea, habría que añadir un meta description como vimos en clase, y pienso que tendríamos que decidir el tamaño de letra que pones ya que ahora mismo los posts son especialmente grandes en comparación a los links.

Está corregido ya